/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Harjoitustyo.kayttoliittyma.kaynnistys;

import Harjoitustyo.kayttoliittyma.Kayttoliittyma;
import Harjoitustyo.kayttoliittyma.OptionsAlku;
import Harjoitustyo.kayttoliittyma.TallennaKuuntelija;
import Harjoitustyo.sovelluslogiikka.Sovelluslogiikka;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author JH
 */
public class KayttoliittymaLoader extends javax.swing.JFrame implements Runnable {

    Sovelluslogiikka logiikka;
    Scanner scan;
    
    /**
     * Creates new form KayttoliittymaLoader2
     */
    public KayttoliittymaLoader(Sovelluslogiikka logiikka) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayttoliittymaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayttoliittymaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayttoliittymaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayttoliittymaLoader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        this.logiikka=logiikka;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uusiPeli = new javax.swing.JButton();
        lataaPeli = new javax.swing.JButton();
        lopetaPeli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        uusiPeli.setText("Uusi peli");
        uusiPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiPeliActionPerformed(evt);
            }
        });

        lataaPeli.setText("Lataa peli");
        lataaPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lataaPeliActionPerformed(evt);
            }
        });

        lopetaPeli.setText("Lopeta");
        lopetaPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaPeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lopetaPeli, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lataaPeli, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(uusiPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uusiPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lataaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lopetaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uusiPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiPeliActionPerformed
        OptionsAlku options = new OptionsAlku(logiikka);
        SwingUtilities.invokeLater(options);
        this.dispose();
    }//GEN-LAST:event_uusiPeliActionPerformed

    private void lataaPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lataaPeliActionPerformed
        JFileChooser valitsin = new JFileChooser();
        int ok = valitsin.showOpenDialog(this);
        
        if (ok==JFileChooser.APPROVE_OPTION) {
            File file = valitsin.getSelectedFile();
            try {
                scan = new Scanner(file);
                String sisalto="";
                while (scan.hasNextLine()) {
                    sisalto=sisalto+scan.nextLine()+"\n";
                }
                
                //save virheellinen
                try {
                    logiikka.getTilanne().asetaAsetukset(sisalto);
                    Kayttoliittyma kl = new Kayttoliittyma(logiikka);
                    SwingUtilities.invokeLater(kl);

                    this.dispose();
                
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Tiedosto ei ole kelvollinen.");
                }
                                
            } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Tiedostoa ei voi avata.");
            }
            
                     
        }
    }//GEN-LAST:event_lataaPeliActionPerformed

    private void lopetaPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaPeliActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lopetaPeliActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void run() {
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lataaPeli;
    private javax.swing.JButton lopetaPeli;
    private javax.swing.JButton uusiPeli;
    // End of variables declaration//GEN-END:variables
}
